app8/urls.py
from django.urls import path
from . import views

app_name = "story8"

urlpatterns = [
    path('BookSearch/', views.story8, name = 'story8'),
]

app9/urls.py
from django.urls import path
from . import views

app_name = "app9"

urlpatterns = [
    path('acc', views.account, name="acc"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name='logout')
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app8.urls')),
    path('app9/', include('app9.urls')),
]

app8/models.py
from django.db import models

# Create your models here.

app9/models.py
from django.db import models

# Create your models here.

app8/views.py
from django.shortcuts import render
from django.http import JsonResponse

# Create your views here.
def story8(request):
    return render(request, "index.html")

app9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def account(req):
    error = "Username atau Password anda salah"
    user = req.user
    if user.is_authenticated:
        return redirect('app9:login')
    if req.method == 'POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req, user)
            return redirect('app9:login')
    else:
        form = AuthenticationForm()
    return render(req, 'account.html', {'form':form, 'error':error})

def log_in(req):
    return render(req, 'login.html')

def log_out(req):
    logout(req)
    return redirect('app9:acc')

app8/templates/index.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
        <script type = "text/javascript" src ="{% static 'index.js' %}"></script>
        <title>Search Book Engine</title>
        <style>
        body {
            font-family: 'Nunito', sans-serif !important;
            background: wheat;
            }
        </style>
    </head>
    <body>
        <div class="text-center" style="margin-top: 30px;">
                <h1>Search Book Engine</h1>
                <input id="search" type="text" placeholder ="search...">
                <br>
                <input class ="btn btn-outline-light text-dark btn-sm" style = "margin-top: 10px; margin-bottom: 10px;" type="submit" id="button" value="search">
        </div>
        
        <table class="table table-striped table-bordered table-info">
            <thead>
              <tr>
                <th width = "20%" class="title text-center">Book Title</th>
                <th width = "40%" class="desc text-center">Description</th>
                <th width = "10%" class="link text-center">Author</th>
                <th width = "10%" class="img text-center">Book Cover</th>
              </tr>
              
            </thead>

            <tbody>
            </tbody>
        </table>
    </body>
</html>

app9/templates/account.html
{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>Search Book Engine</title>
        <style>
        body {
            font-family: 'Nunito', sans-serif !important;
            background: wheat;
            }
        </style>
</head>

{% block content %}
<div class="text-center" style="margin-top: 30px;">
    <h1>Hello world!</h1>
    <h2>Log in</h2>
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action='{% url "app9:acc" %}'>
        {% csrf_token %}
        <label>Username</label>
        <br>
        {{ form.username }}
        <br>
        <label>Password</label>
        <br>
        {{ form.password }}
        <br>
        <input type="submit" value="Log in" class="button">
    </form>
</div>
{% endblock %}

app9/templates/login.html
{% load static %}

{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>Search Book Engine</title>
        <style>
        body {
            font-family: 'Nunito', sans-serif !important;
            background: wheat;
            }
        </style>
</head>

{% block content %}

<div class="text-center" style="margin-top: 30px;">
    {% if user.is_authenticated %}
    <h1>Selamat datang, {{user}}</h1> 
    <a href="{% url 'app9:logout' %}">
        <div class='logout'>
            Log out
        </div>
    </a>
    {% else %}
    <h1>Log in dulu ya!</h1>
    <a href="{% url 'app9:acc' %}">
        <div class='login'>
            Log in
        </div>
    </a>
    {% endif %}

</div>
{% endblock %}